version: '3.8'

services:
  sua-aplicacao-s3:
    build: .
    restart: "no"
    env_file:
      - .env

  airflow-scheduler:
    user: "${UID}:${GID}"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
      - ./src: /usr/local/airflow/src
      - ./data:/usr/local/airflow/data

  airflow-webserver:
    user: "${UID}:${GID}"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
      - ./src: /usr/local/airflow/src
      - ./data:/usr/local/airflow/data

  airflow-worker:
    user: "${UID}:${GID}"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
      - ./src: /usr/local/airflow/src
      - ./data:/usr/local/airflow/data
